function VcLp(){function p(a){var b=document.URL.match(/[?&]vc_lpp=([^&]+)/);if(null==b)r(void 0,a);else{var d=b[1];b="";try{b=t(d)}catch(u){r(void 0,a);return}r(b,a);a=Math.floor((new Date).getTime()/1E3);b=b.split(",");d=b.length;for(var e=0;e<d;e++)a:{var c=b[e],l=a,f=c.split("&");if(!(5>f.length)){var h=0,k=1,g=2,m=3;f[0].match(/^[1-9]$/)&&(h=f[0],k=2,g=3,m=4,c=f[5]);k=parseInt(f[k],16);if(!(isNaN(k)||l>k+10800||(l=parseInt(f[g],16),isNaN(l)||(m=parseInt(f[m],16),isNaN(m))))){if(2==h&&(f=f[6]))try{g=
h=void 0;var n=document.URL,v=n.match(/[?&]vo__ih=([^&]+)/);null!=v&&(h=v[1]);var w=n.match(/[?&]vo__uri=([^&]+)/);null!=w&&(g=w[1]);path=t(f);n="https://ptb.valuecommerce.com"+path;void 0!==h&&(n+="&ih="+h);void 0!==g&&(n+="&vcurl="+g);navigator.sendBeacon(n)}catch(u){}f="";try{f=(new Date(1E3*m)).toUTCString()}catch(u){break a}h=document.domain.split(".");g=h.length;3<=g&&(k="."+h[g-3]+"."+h[g-2]+"."+h[g-1],x(l,f,"l",c,k));2<=g&&(k="."+h[g-2]+"."+h[g-1],x(l,f,"l",c,k));"undefined"!=typeof localStorage&&
null!=localStorage&&localStorage.setItem("_vc_lsc_"+l,"ls"+c+"&"+m)}}}}}function r(a,b){if("undefined"!=typeof a){var d="undefined"!==typeof a?"?p="+encodeURIComponent(a)+"&":"?";"undefined"!==typeof b&&(d+="vf="+encodeURIComponent(b)+"&");var e="";try{var c=document.createElement("a");c.href=document.URL;e=encodeURIComponent(c.protocol+"//"+c.hostname+"/")}catch(l){}d+="_s="+e+"&_rand="+Math.random();c="https://b.imgvc.com/l"+d;document.createElement("img").src=c}}function x(a,b,d,e,c){document.cookie=
"_vc_citi_"+a+"="+d+e+"; expires="+b+"; path=/; domain="+c}function q(a){if(65<=a&&90>=a)return a-65;if(97<=a&&122>=a)return a-97+26;if(48<=a&&57>=a)return a-48+52;if(45==a)return 62;if(95==a)return 63;throw Error("unvalid char");}function t(a){var b="";try{var d=a;d=d.replace(/-/g,"+").replace(/_/g,"/");return decodeURIComponent(y(atob(d)))}catch(l){}d=0;for(var e=a.length;d<e;d+=4){var c=[0,0,0,0];c[0]=q(a.charCodeAt(d));e>d+1&&(c[1]=q(a.charCodeAt(d+1)));e>d+2&&(c[2]=q(a.charCodeAt(d+2)));e>d+
3&&(c[3]=q(a.charCodeAt(d+3)));d+3<e?(b+=String.fromCharCode((c[0]<<2)+(c[1]>>4)&255),b+=String.fromCharCode((c[1]<<4)+(c[2]>>2)&255),b+=String.fromCharCode((c[2]<<6)+c[3]&255)):d+2<e?(b+=String.fromCharCode((c[0]<<2)+(c[1]>>4)&255),b+=String.fromCharCode((c[1]<<4)+(c[2]>>2)&255),b+=String.fromCharCode(c[2]<<6&255)):d+1<e?(b+=String.fromCharCode((c[0]<<2)+(c[1]>>4)&255),b+=String.fromCharCode(c[1]<<4&255)):d<e&&(b+=String.fromCharCode(c[0]<<2&255))}return b.replace(/\0/g,"")}function y(a){return a.replace(/[^a-zA-Z0-9@*_+\-./]/g,
function(b){b=b.charCodeAt(0);return 255>=b?"%"+("00"+b.toString(16)).slice(-2).toUpperCase():"%u"+("0000"+b.toString(16)).slice(-4).toUpperCase()})}this.finishLoad=function(){var a=document.createElement("img"),b=document.createElement("canvas");a.addEventListener&&"undefined"!=typeof b?(a.addEventListener("load",function(){try{b.width=a.naturalWidth;b.height=a.naturalHeight;b.getContext("2d").drawImage(a,0,0);var d=b.toDataURL("image/png");p(d.replace(/^data:image\/(png|jpg);base64,/,""))}catch(e){p(void 0)}},
!1),a.crossOrigin="anonymous",a.style.display="none",a.src="https://a.imgvc.com/i/bf.png?v=1",document.getElementsByTagName("body")[0].appendChild(a)):p(void 0)}}
if("undefined"==typeof vclpObj){var vclpObj=new VcLp;if(document.addEventListener)"loading"!=document.readyState?vclpObj.finishLoad():document.addEventListener("DOMContentLoaded",vclpObj.finishLoad,!1);else if(document.attachEvent){var CheckReadyState=function(){"complete"==document.readyState&&(document.detachEvent("onreadystatechange",CheckReadyState),vclpObj.finishLoad())};document.attachEvent("onreadystatechange",CheckReadyState);(function(){try{document.documentElement.doScroll("left")}catch(p){return}document.detachEvent("onreadystatechange",
CheckReadyState);vclpObj.finishLoad()})()}else vclpObj.finishLoad()};
